### ISSUE TITLE
New users are confused about the non-error they get if they try to log in using a Slack other than codebuddiesmeet.slack.com

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/codebuddies#224] opened 2016-09-28 07:33 UTC
If you're a member of multiple Slack teams, and if you're not currently logged into codebuddiesmeet.slack.com, clicking on "Sign In" and then on one of the other Slack teams will result in the popup disappearing, and the home page not changing. There is no error message.

This is confusing for new users who might think they're already logged in, or can't remember the name of the Slack team (`codebuddiesmeet`, not `codebuddies`) to log in.

Two potential ways to address this problem:
1) Allow users to log in using any Slack team. (Disadvantage: it'll be hard to tell who they are on Slack.)
2) Insert a javascript popup that loads before the signin popup, with some reminders (maybe a screenshot?) about which Slack to choose to log in with, and the team name of the Slack, and how to create an account if the user isn't a member of the Slack.)

I think I lean towards solution #2, but I haven't dug into whether adding a callback function that pops open a popup reminder is possible yet, or whether we'd need to fake the button and add in a second link to sign in after the popup reminder.

(Side thought: do we really want to have Slack be the only option for creating an account/signing in?)

**Comment by adachiu** [comment] 2016-09-29 03:47
@lpatmo Can we change the "codebuddiesmeet" name to "codebuddies" ? Or is it taken? Slack says [here](https://get.slack.help/hc/en-us/articles/201663443-Change-your-team-name-or-domain) that you can change the team name.

**Comment by lpatmo** [comment] 2016-09-29 03:50
@adachiu I had tried before, but `codebuddies` had already been taken! This was in March 2015. :/

**Comment by adachiu** [comment] 2016-09-29 04:05
@lpatmo Tried to search for the codebuddies slack team, but couldn't find anything. Maybe it's private. If it's unused, I wish we could contact the owner to give us the name..

**Comment by wuworkshop** [comment] 2016-10-01 00:55
@adachiu if you go here https://codebuddies.slack.com/ and look at the bottom, it says:
"If you have an @codebuddies.de email address, you can create an account." So whoever owns that domain name probably owns the Slack name.

**Comment by adachiu** [comment] 2016-10-01 01:05
@wuworkshop I saw that and already contacted someone on Twitter, but he said he was once related to the @codebuddies.de and is no longer. I'm asking him if he knows who has that email address so I can directly ask him/her if they can free up the team name if it's not used!

**Comment by wuworkshop** [comment] 2016-10-04 21:23
I just realized the copy on the homepage says:
> Select CodeBuddies or sign into the codebuddiesmeet.slack.com team.

What is "Select CodeBuddies" even referring to? O-o Wouldn't that just make people think the Slack url is "codebuddies.slack.com"?

**Comment by adachiu** [comment] 2016-10-04 22:40
@wuworkshop I believe it's because of this window which the user needs to click on "CodeBuddies" to proceed further

![screen shot 2016-10-04 at 3 37 50 pm](https://cloud.githubusercontent.com/assets/13413986/19095093/a8f3365e-8a48-11e6-8712-76fccf692152.png)

**Comment by techtolentino** [comment] 2016-10-20 09:45
I'm curious what the current status of this is. I have not been able to reproduce the non-error and I'm wondering what I'm missing. 

- I clicked on the _Sign in_ link on the homepage
- I Authorized using my own personal Slack team (`randytolentino.slack.com`)
- I was signed in to CodeBuddies through my own Slack team and not my codebuddiesmeet.slack.com account

**Comment by lpatmo** [comment] 2016-10-27 06:27
Thanks for testing this out, @techtolentino! And sorry for the slow response.

I tested again signing into two different alternate Slack teams, and wasn't able to log in. (After you logged in using randytolentino.slack.com, did you see the list of hangouts, out of curiosity? Or did you remain on the home page?)

I wonder if this might be attributed to different permission settings on Slack teams, since I recently noticed a username on the production site that wasn't DM-able on the CodeBuddies Slack -- meaning that the user was probably logged in via another Slack.

**Comment by lpatmo** [comment] 2016-10-27 06:29
(Btw, this issue is related to the newly-created #370)

**Comment by billglover** [comment] 2019-02-24 14:14
I've just signed in with a different Slack team and can log in to CodeBuddies without issue. It identifies my profile correctly (presume the email address) and show the list of hangouts I completed when identified through GitHub.

I'm closing this as it is old and I'm not able to replicate but please feel free to re-open if this is an issue for you.

**Closed by billglover** 2019-02-24 14:14 UTC
Labels: bug, discussion, help wanted, high-priority, needs code review, not-claimed
